### PR TITLE
Add Simplified Chinese trans

### PR DESCRIPTION
**Pull request by wzxjohn**

### CODE REVIEW

**Comment by Luceos** [comment]
@wzxjohn thank you so much. Could you explain the difference between this PR and the [cn](https://github.com/flagrow/upload/blob/master/locale/cn.yml) file?

**Comment by wzxjohn** [comment]
1. The Simplified Chinese trans should put in zh.yml to let system use it.
2. Trans new words in new version.

**Comment by tony199555** [comment]
OK. I will try to PR with the right file name and do some more updates on it.

**Comment by Luceos** [comment]
Cool, thanks! Closing this one for now.

**Pull request closed without merging**
