### PR TITLE
Remove region limit in AwsS3.php

### PR DESCRIPTION
**Pull request by teklab-de**
This change remove the "one" region limit. The best connection and region is now selected automatically.

### CODE REVIEW

**Comment by teklab-de** [comment]
You only need the region for the upload. I just tested it. The line 27 in the file AwsS3.php can also be deleted.

`$region = $this->adapter->getClient()->getRegion();`

You can test my changes at community.teklab.de . Create a new post and upload a file.

**Comment by teklab-de** [comment]
You create a bucket in AWS and it is automatically accessible from all other regions. You don't have to create extra permissions for regions. 

grafik

Who uses its bucket under s3.amazonaws.com/regionxyz/bucketname, can this at any time also over bucketname.s3.amazonaws.com

s3.amazonaws.com/regionxyz/bucketname/foldername = bucketname.s3.amazonaws.com/foldername

**Comment by luceos** [comment]
@exsisto could you confirm this when you have the chance? Much appreciated 😘

**Comment by luceos** [comment]
After some consideration with a dear friend working for AWS I concluded the following:

Not adding the region to the link will cause it to always hit the default region "US east 1" and receive a 307 redirect to the correct region. Aside from increased loading times due to the redirect your assets might be even more impacted in case the region has connection troubles.

On these grounds I think it's unwise to merge. Thank you for the PR and taking the time to explain the reasoning behind it.

**Comment by teklab-de** [comment]
For small communities, the region is certainly okay. But if users come from europe, asia, ..., then the region is not the best way. If the files are bigger than just a few small pictures, you will notice the difference. But ok ;)

**Pull request closed without merging**
